kaliop-uk/ezmigrationbundle

Core/API/Handler/LocationResolverHandler.php, Core/API/LocationResolver/AbstractRepositoryAwareLocationResolver.php, Core/API/LocationResolver/LocationRemoteIdLocationResolver.php, Core/API/LocationResolver/LocationResolverInterface.php, Core/API/Managers/AbstractManager.php, Core/API/Managers/ContentTypeManager.php, DependencyInjection/CompilerPass/LocationResolverCompilerPass.php, EzMigrationBundle.php, Resources/config/services.yml
This PR adds the possibility to define location remote id for values in field settings. This can be easily extend by tagging services with `ez_migration_bundle.location_resolver` and implementing the `LocationResolverInterface` by them. It does not break the reference handler and is run just before. Later the reference handler could be refactored to `LocationResolver` and the places where value should be resolved as location.
=> Added location resolver. Implemented only for field setting value.

Core/Executor/LocationManager.php
this fix a wrong check as remote ids can be strings. also a dedicated function has been created. param is passed by reference... don't know if you prefer a return instead....
=> add dedicated function to convert the reference matches to valid values

API/LanguageAwareInterface.php, Command/MigrateCommand.php, Core/Executor/ContentManager.php, Core/Executor/ContentTypeManager.php, Core/Executor/RepositoryExecutor.php, Core/Executor/UserGroupManager.php, Core/Executor/UserManager.php, Core/MigrationService.php, Core/ReferenceResolver/CustomReferenceResolver.php, Resources/doc/DSL/ManageContent.yml, Resources/doc/DSL/ManageContentType.yml, Resources/doc/DSL/ManageUsersAndGroups.yml
This patch adds support for language code in migration steps:
```yaml
-
type: content
mode: create
content_type: dossier
main_location: 1234
lang: fre-FR
attributes:
- titre: Some title
```
It also adds supports setting of a default language code to use, as a console command option, if no language is set in yml DSL:
```
php ezpublish/console kaliop:migration:migrate --default-language=fre-FR MyBundle
```
=> Added support for language code

Core/Executor/ContentManager.php, Core/Executor/ContentTypeManager.php, Resources/doc/DSL/ManageContent.yml, Resources/doc/DSL/ManageContentType.yml, Tests/dsl/good/UnitTestOK003_contentType.yml, Tests/dsl/good/UnitTestOK004_content.yml
When adding content alwaysAvailable is not respecting the content type default.  This allow setting alwaysAvailable or falling back to the default from the content type.
=> Fix handling of alwaysAvailable on content create

API/MigrationGeneratorInterface.php, Command/AbstractCommand.php, Command/GenerateCommand.php, Core/Executor/ContentTypeManager.php, Core/Executor/RoleManager.php, Core/MigrationService.php, Tests/phpunit/1_GenerateTest.php, Tests/phpunit/CommandTest.php
Is a part of issue: https://github.com/kaliop-uk/ezmigrationbundle/issues/34
Requires: https://github.com/ezsystems/ezpublish-kernel/pull/1893
=> Extend GenerateCommand to generate migration for existing content types

Core/Executor/UserGroupManager.php, Core/Executor/UserManager.php, Core/Matcher/ContentMatcher.php, Core/Matcher/UserGroupMatcher.php, Resources/config/services.yml, Resources/doc/DSL/ManageUsersAndGroups.yml
As in our project we do not want to rely on autoincrement id's related to user group migrations (e.g. as resorting might break migrations), we enhanced the existing migration possibilities for user groups to allow usage of remote_id for:
- user group's "parent_group_id": if string provided, it is considered referencing a user group's remote_id instead of it's id
- allowing matching on "content_remote_id" for user group update/delete 
- allowing usage of user group remote_id in user's "groups" when creating/updating
I hope this PR work is acceptable, otherwise I am open to improvement ideas and suggestions. Did not find any unit tests to enhance or adapt, tested running several migrations using the new possibilities though.
=> Allowing remote_id for user group related migrations

Core/ComplexField/EzRelation.php
The generate command generates following attribute if the relation is empty:
`
-
attributes:
relation:
destinationContentId: null
`
Than the isset function returns false and the import runs into an exception.
=> Fix: Generated migration with empty relation field caused error

Core/MigrationService.php, Tests/dsl/UnitTestOK018_defaultLanguage.yml, Tests/phpunit/2_MigrateTest.php
The `--default-language` option does not really work for `kaliop:migration:migrate` currently.
If you set the `lang` for a content, then the executor sets the current language to that lang and never resets it. So it will use this lang as default for all following contents, ignoring the default language.
I just put a languageCode reset into the loop. Reset the language for the current executor before every step, so the `execute` method will always check if it should use default lang or not.
I made a phpunit unit test for this and refactored the tests a bit to remove some code duplications.
In the test dsl file you can see I create 2 contents. The default language is "def-LA".
I create the first content with `eng-GB` and omit the lang for the second content, so I expect the default here, so …
=> Fix default language for migrations

README.md
=> Fix bad naming of bundle. Doctrine instead of Symfony

.travis.yml
PHP7 is known to be faster so run code coverage on PHP7 to reduce total time taken by travis
=> Run code coverage on PHP7 to leverage performance increase from latest version

Core/Executor/ContentTypeManager.php
I'm facing an issue whereby I can't use a reference for `field-settings`. It looks like the references are resolved first and then the unresolved settings get used in `hashToFieldSettings`
I'm unsure on how to add a test for this to the existing phpunit setup but if someone could help that would be much appreciated.
This is the migration script I'm using that causes the issue:
```
-
mode: create
type: content
content_type: folder
main_location: 43 #Media
priority: 0
attributes:
- name: Videos
references:
-
identifier: video_location_id_ref
attribute: location_id
-
type: content_type
mode: update
identifier: article
attributes:
-
type: ezobjectrelation
name: Video
identifier: video
field-settings:
selectionRoot: "reference:video_location_id_ref"
```
=> Use field settings that already have references resolved

Resources/doc/DSL/Tags.yml
Without the array structure in references you get the following error on migrations with tags : `Illegal string offset 'attribute' in file /var/www/interpol/vendor/kaliop/ezmigrationbundle/Core/Executor/RepositoryExecutor.php line 169`
Note : I also cleaned the comments about deletion in the update block
=> Fix for references in Tags migration documentation

Resources/doc/DSL/ContentTypes.yml
Since v1.11.0 it is possible to restrict selectable content types for single object relations fields: https://doc.ezplatform.com/en/1.12/releases/ez_platform_v1.11.0/
So `ezobjectrelation` accepts the `selectionContentTypes` option too, like `ezobjectrelationlist`. 
No code changes needed for kaliop for this.
=> Update dsl documentation

Resources/doc/DSL/ContentTypes.yml
i'm playing with content types and attribute names updating. it turns out that kmb don't like square brackets. probably is yaml the one which don't like them. 
Using square brackets didn't allow execute the migration with this error
```
Unexpected characters (: "Name", "esl-ES": "Nombre" ]) at line 9 (near "name: [ "eng-GB": "Name", "esl-ES": "Nombre" ]").
```
Also, fixed a typo `sting` instead of `string`
=> fix doc for the ContentTypes dsl

Resources/doc/DSL/ContentTypes.yml
eZ 2 introduced a configurable limit for the `ezobjectrelationlist` field type. Kaliop already can configure this limit, just need this doc update to make it clear. No other changes needed for this, but only works from eZ 2.0 aka kernel 7.0.0.
https://github.com/ezsystems/ezpublish-kernel/blob/v7.0.0/eZ/Publish/Core/FieldType/RelationList/Type.php#L51
=> Update ezobjectrelationlist dsl

composer.json
let's try adding this symfony version as conflicting one. i tried it locally and test seemed to pass. let's open this pr to see what travis thinks.
=> add symfony 3.4.12 as conflicting version

composer.json
i'm playing with some other projects that requires this php-parser version. 
do you think this could lead to some problems here? if so, please discard this.
=> allow version 4 for nikic php-parser

Tests/travis/setup-config.sh
i found that the error we were getting in the test was because when it tried to validate the eztags field added in the migration, the `Null/Type` were used instead of the netgen tags validator. 
Without digging in much more details, i decided to try to move the load of the netgen tags bundle after tall the ez systems bundles. in fact, there was a comment there saying that was the idea, but the result was that the Netgen Bundle was before the ezsystems one in the generated AppKernel. 
This makes the test pass in my computer, php 7.2. I hope not break anything with this, but let's see what travis says...
=> fix travis testing by changing orders of the bundles

.travis.yml, Core/Executor/ContentManager.php, Tests/dsl/bad/execution/UnitTestKO013_multilang_fields.yml, Tests/dsl/bad/execution/UnitTestKO014_multilang_fields_wrong_lang.yml, Tests/dsl/bad/execution/UnitTestKO015_multilang_fields_missing_field.yml, Tests/dsl/good/UnitTestOK009_language.yml
Multilang support for content create/update
todo:
=> Multilang support for content create/update

Resources/doc/DSL/Tags.yml
`id` wasn't specified as a possible references attribute. Without it it's hard to put a tag as a child of another tag.
=> `id` missing as possible references attribute for tags.

Core/Matcher/UserMatcher.php
The logic was already implemented, but it wasn't added to the list of allowedConditions.
=> Allow usergroup_id matching for users

Resources/doc/DSL/UsersAndGroups.yml
Hey,
I stumbled over the fact, that the given password string in a kaliop migration will be automatically hashed. I think this should be mentioned in the docs so here is the change.
=> Added note for hashing passwords in kaliop migrations

Resources/config/services.yml
Fixes for EzPlatform 3.0
fixes for:
```                                                                
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]   
The "ez_migration_bundle.migration_service" service or alias has been remov  
ed or inlined when the container was compiled. You should either make it pu  
blic, or stop using the container directly and use dependency injection ins  
tead. 
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]   
The "ez_migration_bundle.step_executed_listener.tracing" service or alias h  
as been removed or inlined when the container was compiled. You should eith  
er make it public, or stop using the container directly and use dependency   
injection instead.  
```
which occurs during ezp-ee-demo …
=> Fixes for EzPlatform 3.0

Command/GenerateCommand.php, DependencyInjection/eZMigrationExtension.php, README.md, Tests/bootstrap.php, Tests/config/common/services.yml, Tests/environment/setup-ez-config.sh, eZMigrationBundle.php
Bundle name should follow naming convention https://symfony.com/doc/current/bundles/best_practices.html#bundle-name
The issue occurs when trying to install this bundle on sf4 using symfony flex,
https://github.com/symfony/flex/blob/master/src/SymfonyBundle.php#L89
https://github.com/symfony/flex/blob/master/src/SymfonyBundle.php#L103
code expects that the bundle file will follow
namespace  "Kaliop\eZMigrationBundle\" -> one of those:
0 => "Kaliop\eZMigrationBundle\eZMigrationBundle"
1 => "Kaliop\eZMigrationBundle\KaliopeZMigrationBundle"
related issues 
```
!!                                                                                 
!!    Case mismatch between loaded and declared class names: "Kaliop\eZMigrationB  
!!    undle\DependencyInjection\eZMigrationExtension" vs …
```
=> [ezp-3] Fixed Bundle name

Core/ReferenceResolver/EmbeddedRegexpReferenceResolverTrait.php
I have this error on PHP7.4 with Symfony 3.4.37
```
Compile Error: Access level to Kaliop\eZMigrationBundle\Core\ReferenceResolver\EmbeddedRegexpReferenceResolverTrait::getR  
eferenceValue() must be public (as in class Kaliop\eZMigrationBundle\Core\ReferenceResolver\PrefixBasedResolver)
```
=> Fix compiling error

Core/FieldHandler/EzCountry.php, Resources/config/services.yml, Resources/doc/DSL/Contents.yml, Tests/dsl/good/UnitTestOK004_content.yml
Adds support for ez country field allowing entering either a single alpha2 (for non multiple calues cases) or an array of codes for the case the field allows multiple values
=> issue-224: add support for ezcountry field

Core/ReferenceResolver/EmbeddedRegexpReferenceResolverTrait.php
this backports the fix to issue #232 to version 5.7 of the bundle (which works correctly with ezworkflowengine bundle), it should be tagged as 5.7.4 if the PR is accepted.
=> fix: backport fix to issue #232 to bundle version 5.7
