Core/API/Managers/ContentTypeManager.php

Handling missing validation configuration field defintion for content type.

Handling validation configuration field defintion for content type

---

Core/API/Managers/ContentManager.php

ContentUpdateStruct does not have contentType so we have to get it from ContentTypeService. For getting the content object by remote id it is already the ContentInfo.

Fixed ContentManager for update

---

Core/API/ComplexFields/EzRichText.php
Resources/config/services.yml

Hello,
Just a quick complex field handler same as the ezxmlfield one to handle the new ezrichtext field.

Add support for the new eZRichText field type.

---

Core/API/ComplexFields/EzAuthor.php
Resources/config/services.yml
Resources/doc/DSL/ManageContent.yml

Adding a new complex field handler to support the ezauthor field type.

Adding support for ezauthor field type in content creation.

---

Core/API/Managers/ContentManager.php

Looks $this was the entire container there...

Fix update problem. Attributes were not get from the yml file because bad ref

---

Core/API/Managers/ContentManager.php

This will allow create a content and update another setting a relation to it, for example.

Allow update use references for single fields

---

Core/API/Collection.php
Core/API/ContentCollection.php
Core/API/ContentMatcher.php
Core/API/LocationCollection.php
Core/API/Managers/LocationManager.php
Resources/config/services.yml
Resources/doc/DSL/ManageLocation.yml

Implements #18
Allow location create with several conditions. see updated dsl for explanation.

Add match location operations

---

Core/Executor/LocationManager.php

Reverts kaliop-uk/ezmigrationbundle#35

Revert "add dedicated function to convert the reference matches to valid values"

---

Core/Executor/ContentManager.php
Core/Executor/LocationManager.php

some changes in content and locationmanager to get references properly

fixed bad calls to isReference and getReference methods

---

Resources/doc/DSL/ManageContentType.yml

The current URL leads to a 404 on the eZ wiki

Update URL for field type reference

---

Core/Executor/LocationManager.php
Resources/doc/DSL/ManageLocation.yml

implements #62: Allow update remote_id for location

---

Resources/doc/DSL/ManageContent.yml

Removed duplicate content_id and content_remote_id lines from the match sections.

Remove duplicate attributes

---

API/Collection/ObjectStateCollection.php
API/Collection/ObjectStateGroupCollection.php
Core/Executor/ObjectStateGroupManager.php
Core/Executor/ObjectStateManager.php
Core/Matcher/ObjectStateGroupMatcher.php
Core/Matcher/ObjectStateMatcher.php
Resources/config/services.yml
Resources/doc/DSL/ManageObjectStatesAndGoups.yml

Ability to manage `ObjectState`'s and `ObjectStateGroup`'s.

Object state manager for 2.x

---

Core/Executor/ContentTypeGroupManager.php
Core/Executor/ContentTypeManager.php
README.md
Resources/config/services.yml
Resources/doc/DSL/ManageContentTypeGroup.yml
Tests/dsl/good/UnitTestOK010_content_type_group.yml

Adds support for adding and deleting content type groups.
#82

Content type groups

---

Core/Executor/TagManager.php
Resources/doc/DSL/ManageTags.yml

Fix reference resolver in tag manager
Doc update for tag management

Fix : reference resolver in tag manager

---

Core/Executor/UserGroupManager.php

possibility to assign section to new user group

assign section to new user group

---

Command/MigrateCommand.php

Frist tiny feature to improve handling

Add shortcuts to command migrate

---

Core/Executor/ContentTypeManager.php

Allow the set of all translations for content types and content type fields
e. g.
```
-
type: content_type
mode: create
content_type_group: Content
identifier: article
names:
eng-GB: Article
ger-DE: Artikel
descriptions:
eng-GB: 'Article content type'
ger-DE: 'Artikel Inhaltsart'
name_pattern: '<short_title|title>'
url_name_pattern: ''
is_container: true
lang: eng-GB
attributes:
-
identifier: title
type: ezstring
names:
eng-GB: Title
ger-DE: Titel
descriptions:
eng-GB: 'Header of the article'
ger-DE: 'Überschrift des Artikels'
required: true
searchable: true
info-collector: false
disable-translation: false
category: ''
position: 1
default-value: 'New article'
field-settings: {  }
validator-configuration:
StringLengthValidator: { maxStringLength: 255, minStringLength: null }
```

Content Type Manager: Support multilingual Names/Descriptions in one step

---

Tests/helper/AssertExecutor.php

Possibility to use PHPUnit >= 6.x

support for PHPUnit >= 6.x

---

Core/Executor/ContentTypeManager.php
Tests/dsl/eztags/v3/UnitTestOK019_eztagsv3.yml

Possibility to use reference in validator/subTreeLimit for eztags v3

Possibility to use reference in validator/subTreeLimit for eztags v3

---

Core/Executor/ContentTypeManager.php

Split off from https://github.com/kaliop-uk/ezmigrationbundle/pull/127

Content Type Manager: * support for the remove_attributes setting

---

Core/Executor/ContentTypeManager.php

setContentTypeGroup and unsetContentTypeGroup only works after the publishContentTypeDraft call.

Fix: ContentTypeManager::setContentTypeGroup/unsetContentTypeGroup usage

---

Core/Executor/ContentManager.php

Fixes https://github.com/kaliop-uk/ezmigrationbundle/issues/173

Fix error in content modification_date

---

Core/Matcher/ContentVersionMatcher.php

See [Issue 179](https://github.com/kaliop-uk/ezmigrationbundle/issues/179)

Fix for mismatched method declarations

---

Core/Matcher/QueryBasedMatcher.php
Resources/doc/DSL/Contents.yml
Resources/doc/DSL/Locations.yml

Making group matching work for matchers based on QueryBasedMatcher and updating the DSL doc.

Fix group matching #210

---

Core/Matcher/AbstractMatcher.php
Core/Matcher/ContentMatcher.php
Core/Matcher/LocationMatcher.php

https://github.com/kaliop-uk/ezmigrationbundle/issues/237

fix array objects with php7.4
